### ISSUE TITLE
v4.0

### ISSUE THREAD

**Issue by Yash3667** [hgst/libzbc#10]
When I was using v4.0 on an emulated SATA drive, all the tests run. However, zbc_report_zones listed 0 zones. gzbc showed no zones.

Switching to v2.0 and everything seems to work.

Can anybody reproduce this problem?

**Comment by hgst** [comment]
Hi Yash3667,

For an emulated device, zbc_set_zones must be executed before using the device. This is true for both the tests and the tools. I checked again just now and everything seem to be working fine.
1) Execute zbc_set_zones
2) Run the tests -> all pass
3) run zbc_report_zones -> no problems

Is this the sequence of command you executed ? If not, could you please tell us the precise sequence of commands to recreate the problem ?

Note that currently as the zone information for emulated devices is stored in /tmp, the zone information may not be persistent across reboots of the host machine. After rebooting, running again zbc_set_zones is required. We are aware of this issue and will release a fix soon (storing the zone information in another location).

Best regards.

**Comment by Yash3667** [comment]
Hi,

I ran the commands in the order posted. All tests do succeed, but zbc_report_zones and gzbc list no zones.

I have attached a terminal log script. Please have a look
[V4Test.txt](https://github.com/hgst/libzbc/files/117917/V4Test.txt)

**Comment by hgst** [comment]
Hi Yash3667,

I tried but failed to recreate the problem on my system with the same commands and a similarly sized disk partition.

Can you please check the following:
1) Remove (delete or move to another location) the file /tmp/zbc-<disk>.meta if it exists.
2) Execute zbc_set_zones and check that a new file /tmp/zbc-<disk>.meta exists
3) Check if the zones are reported correctly before running the tests
4) Execute the tests and check again that the file /tmp/zbc-<disk>.meta exists
5) Check again zbc_report_zones result

The reason for step (1) is that I noticed that zbc_set_zones does seem to get the emulated drive information from an existing meta file if one is found rather than systematically getting the information from the emulated drive/file. This may be the cause of your problem.

Also, if zbc_report_zones fails, the output of "zbc_report_zones -v" would be useful (verbose output will help track the origin of the error).

Thank you.

Best regards.

Damien Le Moal, HGST.

**Comment by hgst** [comment]
Hi Yash3667,

Please pull. I just pushed a fix for zbc_set_zones which may resolve your issue.

Thank you.

Best regards.

Damien Le Moal, HGST.

**Comment by Yash3667** [comment]
Hi Damien,

I tried the first solution (removing zbc-x.meta) but it did not solve my problem. I tried the same after you pushed the fix but still the same result.

Have a look at the log. I added the '-v' option as you requested.
[V4Test2.txt](https://github.com/hgst/libzbc/files/119625/V4Test2.txt)

**Comment by hgst** [comment]
Yash,

I still cannot recreate the problem on my system. So I am left with nothing to debug...
It is however very strange that all the tests are reported as "passed" despite zbc_report_zones reporting no zones at all for the emulated device. We are checking this as a hint.

Could you please verify the following:
1) Compare the number of sectors reported by the command "fdisk -l <your disk>" with the number of sectors reported in the output of zbc_set_zones
2) Pull the latest commit and retry the usual command sequence (with debug output)

Note: this latest commit moves the metadata files from /tmp to /var/local.

Thank you.

Best regards.

**Comment by Yash3667** [comment]
Hi,

It should be noted that I am using Ubuntu 14.04.1 with 3.19.8 - Generic Kernel as my setup. Again, I tried a clean install of Ubuntu and tried the commands, and still the same result.

Earlier, when I was using Ubuntu 15.04 with 4.2 - Generic Kernel, a lot of the tests failed, however, zbc_report_zones showed me the zones.

Thanks,
Yash

**Comment by hgst** [comment]
Hi Yash,

We finally succeeded in recreating your problem, using an Ubuntu 14.04 machine (we usually use Fedora distributions on our side).

There were 2 problems:
1) In tools/report_zones/zbc_report_zones, the nr_zones argument was not initialized to 0 (and Ubunutu loader seems to do this by itself while Fedora's one does not)
2) For a fake device, if the function zbc_report_nr_zones was called with nr_zones set to 0, the number of zones reported was always 0.

We fixed both issues and got everything to work properly on Ubuntu (as well as on our usual test systems).

Could you please pull this fix and check  ? I will clause this issue once you confirm a correct execution.

Thank you.

Best regards.

Damien Le Moal, HGST.

**Comment by Yash3667** [comment]
Hi Damien,

I pulled and tried it. Works like a charm!
Still running a few more tests, but everything seems to look good for now!

Thank You,
Yash

**Comment by hgst** [comment]
Hi Yash,

Great !

Best regards.

Damien Le Moal, HGST.
